"""add share token to users

Revision ID: 5d4bdd1cf686
Revises: e3dbc1207600
Create Date: 2026-07-16 21:21:55.465114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4bdd1cf686'
down_revision: Union[str, Sequence[str], None] = 'e3dbc1207600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_share_token'), 'users', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_share_token'), table_name='users')
    op.drop_column('users', 'share_token')
    # ### end Alembic commands ###
