"""add rewatch count, watch parties

Revision ID: 6d5befe5166b
Revises: 37e4bb016b37
Create Date: 2026-07-18 15:19:32.469139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5befe5166b'
down_revision: Union[str, Sequence[str], None] = '37e4bb016b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_parties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_parties_host_id'), 'watch_parties', ['host_id'], unique=False)
    op.create_index(op.f('ix_watch_parties_media_id'), 'watch_parties', ['media_id'], unique=False)
    op.create_table('watch_party_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['watch_parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'user_id', name='uq_watch_party_invite')
    )
    op.create_index(op.f('ix_watch_party_invites_party_id'), 'watch_party_invites', ['party_id'], unique=False)
    op.create_index(op.f('ix_watch_party_invites_user_id'), 'watch_party_invites', ['user_id'], unique=False)
    op.add_column('user_media_status', sa.Column('rewatch_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_media_status', 'rewatch_count')
    op.drop_index(op.f('ix_watch_party_invites_user_id'), table_name='watch_party_invites')
    op.drop_index(op.f('ix_watch_party_invites_party_id'), table_name='watch_party_invites')
    op.drop_table('watch_party_invites')
    op.drop_index(op.f('ix_watch_parties_media_id'), table_name='watch_parties')
    op.drop_index(op.f('ix_watch_parties_host_id'), table_name='watch_parties')
    op.drop_table('watch_parties')
    # ### end Alembic commands ###
