"""add media and user_media_status tables

Revision ID: 7b34be660328
Revises: 1df3852b608e
Create Date: 2026-07-10 19:49:39.480509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b34be660328'
down_revision: Union[str, Sequence[str], None] = '1df3852b608e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id', 'media_type', name='uq_media_tmdb_id_media_type')
    )
    op.create_index(op.f('ix_media_tmdb_id'), 'media', ['tmdb_id'], unique=False)
    op.create_table('user_media_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='uq_user_media')
    )
    op.create_index(op.f('ix_user_media_status_media_id'), 'user_media_status', ['media_id'], unique=False)
    op.create_index(op.f('ix_user_media_status_user_id'), 'user_media_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_media_status_user_id'), table_name='user_media_status')
    op.drop_index(op.f('ix_user_media_status_media_id'), table_name='user_media_status')
    op.drop_table('user_media_status')
    op.drop_index(op.f('ix_media_tmdb_id'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
