"""add rating to watched_episodes

Revision ID: 94d4fd8d98c4
Revises: 98b5c19d8a72
Create Date: 2026-07-13 16:25:25.702212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d4fd8d98c4'
down_revision: Union[str, Sequence[str], None] = '98b5c19d8a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched_episodes', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched_episodes', 'rating')
    # ### end Alembic commands ###
