"""add custom lists

Revision ID: e3dbc1207600
Revises: 94d4fd8d98c4
Create Date: 2026-07-13 16:54:43.831354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3dbc1207600'
down_revision: Union[str, Sequence[str], None] = '94d4fd8d98c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_custom_list_user_name')
    )
    op.create_index(op.f('ix_custom_lists_user_id'), 'custom_lists', ['user_id'], unique=False)
    op.create_table('custom_list_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['custom_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'media_id', name='uq_custom_list_item')
    )
    op.create_index(op.f('ix_custom_list_items_list_id'), 'custom_list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_custom_list_items_media_id'), 'custom_list_items', ['media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_list_items_media_id'), table_name='custom_list_items')
    op.drop_index(op.f('ix_custom_list_items_list_id'), table_name='custom_list_items')
    op.drop_table('custom_list_items')
    op.drop_index(op.f('ix_custom_lists_user_id'), table_name='custom_lists')
    op.drop_table('custom_lists')
    # ### end Alembic commands ###
