"""add watched_episodes table

Revision ID: eed33185aaaa
Revises: 72e0015b1299
Create Date: 2026-07-12 19:39:02.932427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed33185aaaa'
down_revision: Union[str, Sequence[str], None] = '72e0015b1299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_episodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', 'season_number', 'episode_number', name='uq_watched_episode')
    )
    op.create_index(op.f('ix_watched_episodes_media_id'), 'watched_episodes', ['media_id'], unique=False)
    op.create_index(op.f('ix_watched_episodes_user_id'), 'watched_episodes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_episodes_user_id'), table_name='watched_episodes')
    op.drop_index(op.f('ix_watched_episodes_media_id'), table_name='watched_episodes')
    op.drop_table('watched_episodes')
    # ### end Alembic commands ###
